#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : iwd
Version  : 0.6
Release  : 1
URL      : https://www.kernel.org/pub/linux/network/wireless/iwd-0.6.tar.xz
Source0  : https://www.kernel.org/pub/linux/network/wireless/iwd-0.6.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: iwd-bin
Requires: iwd-config
Requires: iwd-data
Requires: iwd-license
BuildRequires : ncurses-dev
BuildRequires : pkgconfig(dbus-1)
BuildRequires : pkgconfig(systemd)
BuildRequires : readline-dev
BuildRequires : systemd-dev

%description
Wireless daemon for Linux
*************************
Compilation and installation
============================

%package bin
Summary: bin components for the iwd package.
Group: Binaries
Requires: iwd-data
Requires: iwd-config
Requires: iwd-license

%description bin
bin components for the iwd package.


%package config
Summary: config components for the iwd package.
Group: Default

%description config
config components for the iwd package.


%package data
Summary: data components for the iwd package.
Group: Data

%description data
data components for the iwd package.


%package license
Summary: license components for the iwd package.
Group: Default

%description license
license components for the iwd package.


%prep
%setup -q -n iwd-0.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1534784768
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1534784768
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/iwd
cp COPYING %{buildroot}/usr/share/doc/iwd/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/iwctl
/usr/bin/iwmon
/usr/libexec/iwd

%files config
%defattr(-,root,root,-)
/usr/lib/systemd/system/iwd.service

%files data
%defattr(-,root,root,-)
/usr/share/dbus-1/system-services/net.connman.iwd.service
/usr/share/dbus-1/system.d/iwd-dbus.conf

%files license
%defattr(-,root,root,-)
/usr/share/doc/iwd/COPYING
